entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: "pardinithales@gmail.com"
      storage: "/letsencrypt/acme.json"
      tlsChallenge: true

api:
  dashboard: true
  insecure: false
